dist: trusty
sudo: required

language: python

branches:
  only:
    - master

services:
  - docker

before_install:
  - docker build --build-arg ST2_REPO=unstable --build-arg CIRCLE_SHA1=${TRAVIS_COMMIT} --build-arg CIRCLE_PROJECT_USERNAME=stackstorm --build-arg CIRCLE_PROJECT_REPONAME=st2-docker -t stackstorm/stackstorm:dev images/stackstorm
  - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
  - docker push stackstorm/stackstorm:dev

install: true

script: true

notifications:
  email:
    recipients:
      - warren.van.winckel@gmail.com
    on_success: never
    on_failure: always
