version: 2
jobs:
  build:
    docker:
      - image: docker/compose:1.23.1
    steps:
      - run: |
          set -x
          printenv | sort
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
