# 
version: 2
jobs:
  build:
    working_directory: /build
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: bin/build.sh
      - deploy:
          name: Deploy image to Docker Hub
          branches:
            only:
              - feature/circleci
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            bin/deploy.sh
deployment:
  trigger_tag:
    tag: /v.*/
