# 
version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docker:17.06.0-ce-git
    branches:
      only:
        - feature/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - run:
          name: Build image
          command: bin/build.sh
      - deploy:
          name: Deploy image to Docker Hub
          command: |
            # Deploy only if tag begins with 'v'
            if [ "${CIRCLE_TAG}" == v* ]; then
              bin/deploy.sh
            fi
