version: 2
jobs:
  build:
    working_directory: /st2-docker-build
    docker:
      - image: docker:17.06.0-ce-git
    branches:
      only:
        - feature/circleci
    steps:
      - checkout
      - setup_remote_docker
          reusable: true
          exclusive: true
      - run:
        rame: Build application Docker image
        command: |
          docker build --cache-from=st2 -t stackstorm/stackstorm:${ST2_VERSION} images/stackstorm/2.3.1
