# 
version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Install bash
          command: apk add --no-cache bash
      - deploy:
          name: Build and Push image to Docker Hub
          command: bin/build-deploy.sh
deployment:
  fake_deploy_for_cci2:
    tag: /v.*/
    name: Build and Push image to Docker Hub
    commands:
      - echo "Make tags run in 2.0"
