# 
version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: docker:17.06.0-ce-git
    branches:
      only:
        - feature/circleci
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          exclusive: true
      - run:
          name: Build image
          command: pwd && ls -l && ls -l /bin && ~/build/bin/build.sh
      - deploy:
          name: Deploy image to Docker Hub
          tag: /^v.*/
          command: |
            if [ "${CIRCLE_BRANCH}" == "feature/circleci" ]; then
              ~/build/bin/deploy.sh
            fi
