---
name: monitor_file
pack: "examples"
description: "Monitor file for change"
enabled: true

trigger:
  parameters:
    file_path: /tmp/watcher.log
  type: linux.file_watch.line

criteria: {}

action:
  parameters:
    cmd: echo "{{trigger}}"
  ref: core.local
