---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-st2-default-files
spec:
  template:
    metadata:
      name: init-st2-default-files
    spec:
      containers:
      - name: init-st2-default-files
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
        command:
        - bash
        - "-c"
        - >-
          mkdir /tmp/st2 &&
          mount -o bind /opt/stackstorm /tmp/st2 &&
          rsync -avi /tmp/st2/packs/ /opt/stackstorm/packs/
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: rabbitmq }
        - configMapRef: { name: postgres }
        volumeMounts:
        - name: st2-packs
          mountPath: /opt/stackstorm/packs
        - name: st2-virtualenvs
          mountPath: /opt/stackstorm/virtualenvs
      volumes:
      - name: st2-packs
        persistentVolumeClaim:
          claimName: st2-packs
      - name: st2-virtualenvs
        persistentVolumeClaim:
          claimName: st2-virtualenvs
      restartPolicy: Never

---
apiVersion: batch/v1
kind: Job
metadata:
  name: init-st2-register-content
spec:
  template:
    metadata:
      name: init-st2-register-content
    spec:
      containers:
      - name: init-st2-register-content
        image: stackstorm/stackstorm:latest
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef: { name: st2 }
        - configMapRef: { name: rabbitmq }
        - configMapRef: { name: postgres }
        env:
        - name: ST2_SERVICE
          value: st2-register-content
        volumeMounts:
        - name: st2-packs
          mountPath: /opt/stackstorm/packs
        - name: st2-virtualenvs
          mountPath: /opt/stackstorm/virtualenvs
      volumes:
      - name: st2-packs
        persistentVolumeClaim:
          claimName: st2-packs
      - name: st2-virtualenvs
        persistentVolumeClaim:
          claimName: st2-virtualenvs
      restartPolicy: Never

